openapi: 3.2.0
info:
  title: epa-csb-server Login API
  version: 8.1.0
  license:
    name: CC0-1.0
  description: U.S. EPA CSB Rebate Forms Application
tags:
- name: Login
paths:
  /login:
    get:
      summary: /login
      responses:
        '302':
          description: Found
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Login
  /login/assert:
    post:
      summary: /login/assert
      parameters: []
      responses:
        '302':
          description: Found
          content:
            text/html:
              schema:
                type: string
                example: <p>Found. Redirecting to <a href="http://localhost:3000/">http://localhost:3000/</a></p>
              examples:
                post_login_assert302Example:
                  summary: Default post_login_assert 302 response
                  x-microcks-default: true
                  value:
                    status: ok
                    message: Example response
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Login
  /login/fail:
    get:
      summary: /login/fail
      parameters: []
      responses:
        '200':
          description: OK
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Login
