openapi: 3.2.0
info:
  title: epa-csb-server Status API
  version: 8.1.0
  license:
    name: CC0-1.0
  description: U.S. EPA CSB Rebate Forms Application
tags:
- name: Status
paths:
  /api/status/app:
    get:
      summary: CSB App Health Check.
      parameters: []
      responses:
        '200':
          description: OK
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Status
  /api/status/bap/sam:
    get:
      summary: CSB SAM.gov Connection Check.
      parameters: []
      responses:
        '200':
          description: OK
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Status
  /api/status/formio/2022/frf:
    get:
      summary: CSB Formio 2022 FRF Schema Check.
      parameters: []
      responses:
        '200':
          description: OK
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Status
  /api/status/formio/2022/prf:
    get:
      summary: CSB Formio 2022 PRF Schema Check.
      parameters: []
      responses:
        '200':
          description: OK
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Status
  /api/status/formio/2022/crf:
    get:
      summary: CSB Formio 2022 CRF Schema Check.
      parameters: []
      responses:
        '200':
          description: OK
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Status
  /api/status/formio/2022/change:
    get:
      summary: CSB Formio 2022 Change Request Form Schema Check.
      parameters: []
      responses:
        '200':
          description: OK
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Status
  /api/status/formio/2023/frf:
    get:
      summary: CSB Formio 2023 FRF Schema Check.
      parameters: []
      responses:
        '200':
          description: OK
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Status
  /api/status/formio/2023/prf:
    get:
      summary: CSB Formio 2023 PRF Schema Check.
      parameters: []
      responses:
        '200':
          description: OK
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Status
  /api/status/formio/2023/crf:
    get:
      summary: CSB Formio 2023 CRF Schema Check.
      parameters: []
      responses:
        '200':
          description: OK
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Status
  /api/status/formio/2023/change:
    get:
      summary: CSB Formio 2023 Change Request Form Schema Check.
      parameters: []
      responses:
        '200':
          description: OK
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Status
  /api/status/formio/2024/frf:
    get:
      summary: CSB Formio 2024 FRF Schema Check.
      parameters: []
      responses:
        '200':
          description: OK
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Status
  /api/status/formio/2024/change:
    get:
      summary: CSB Formio 2024 Change Request Form Schema Check.
      parameters: []
      responses:
        '200':
          description: OK
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Status
