openapi: 3.2.0
info:
  title: U.S. EPA WaterSense Contact API
  description: placeholder
  contact:
    name: US EPA, ELG
  license:
    name: Creative Commons Zero Public Domain Dedication
    url: https://edg.epa.gov/EPA_Data_License.html
  version: 0.0.0
servers:
- url: https://owapps-stage.app.cloud.gov/elg
security:
- basicAuth: []
tags:
- name: Contact
paths:
  /api/contact:
    get:
      summary: Contact
      description: Placeholder
      tags:
      - Contact
      responses:
        '200':
          description: Placeholder
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/glossary.contact'
              examples:
                get_api_contact200Example:
                  summary: Default get_api_contact 200 response
                  x-microcks-default: true
                  value:
                    status: ok
                    message: Example response
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    glossary.contact:
      type: object
      description: Placeholder
      properties:
        Dummy:
          type: string
          title: Dummy
          example: Dummy
          description: Dummy
      required:
      - Dummy
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
