openapi: 3.2.0
info:
  title: epa-csb-server Logout API
  version: 8.1.0
  license:
    name: CC0-1.0
  description: U.S. EPA CSB Rebate Forms Application
tags:
- name: Logout
paths:
  /logout:
    get:
      summary: /logout
      parameters: []
      responses:
        '200':
          description: OK
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Logout
  /logout/callback:
    get:
      summary: /logout/callback
      parameters: []
      responses:
        '200':
          description: OK
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Logout
    post:
      summary: /logout/callback
      responses:
        '200':
          description: OK
      tags:
      - Logout
      parameters: []
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
