openapi: 3.2.0
info:
  title: epa-csb-server Bap API
  version: 8.1.0
  license:
    name: CC0-1.0
  description: U.S. EPA CSB Rebate Forms Application
tags:
- name: Bap
paths:
  /api/bap/sam:
    get:
      summary: Get User's SAM.gov Data from the BAP.
      parameters: []
      responses:
        '200':
          description: A boolean indicating whether any SAM.gov results were returned (to support helpdesk users without SAM.gov entities), along with an array of SAM.gov entities.
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: boolean
                    example: true
                  entities:
                    type: array
                    items:
                      type: object
              examples:
                get_api_bap_sam200Example:
                  summary: Default get_api_bap_sam 200 response
                  x-microcks-default: true
                  value:
                    status: ok
                    message: Example response
        '401':
          $ref: '#/components/responses/Unauthorized'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Bap
  /api/bap/submissions:
    get:
      summary: Get User's Form Submissions Statuses from the BAP.
      parameters: []
      responses:
        '200':
          description: An array of form submission statuses, and other relevant fields.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
              examples:
                get_api_bap_submissions200Example:
                  summary: Default get_api_bap_submissions 200 response
                  x-microcks-default: true
                  value:
                    status: ok
                    message: Example response
        '401':
          $ref: '#/components/responses/Unauthorized'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Bap
components:
  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Unauthorized
