openapi: 3.2.0
info:
  title: epa-csb-server Config API
  version: 8.1.0
  license:
    name: CC0-1.0
  description: U.S. EPA CSB Rebate Forms Application
tags:
- name: Config
paths:
  /api/config/public:
    get:
      summary: Get CSB App Specific Public Configuration (csb App Login Status and Static Content)
      parameters: []
      responses:
        '200':
          description: CSB app login status and static content from S3.
          content:
            application/json:
              schema:
                type: object
                properties:
                  loginEnabled:
                    type: boolean
                    example: true
                  staticContent:
                    type: object
              examples:
                get_api_config_public200Example:
                  summary: Default get_api_config_public 200 response
                  x-microcks-default: true
                  value:
                    status: ok
                    message: Example response
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Config
  /api/config/private:
    get:
      summary: Get CSB App Specific Private Configuration (form Open Enrollment Status, Etc.)
      parameters: []
      responses:
        '200':
          description: Formio base URL and project name, CSB rebate year and open enrollment status.
          content:
            application/json:
              schema:
                type: object
                properties:
                  formioBaseUrl:
                    type: string
                    example: https://api.form.io
                  formioProjectName:
                    type: string
                    example: forms
                  formioPremiumKey:
                    type: string
                    example: secret
                  rebateYear:
                    type: string
                    example: '2024'
                  submissionPeriodOpen:
                    type: object
                    properties:
                      '2022':
                        type: object
                        properties:
                          frf:
                            type: boolean
                            example: true
                          prf:
                            type: boolean
                            example: true
                          crf:
                            type: boolean
                            example: true
                      '2023':
                        type: object
                        properties:
                          frf:
                            type: boolean
                            example: true
                          prf:
                            type: boolean
                            example: true
                          crf:
                            type: boolean
                            example: true
                      '2024':
                        type: object
                        properties:
                          frf:
                            type: boolean
                            example: true
                          prf:
                            type: boolean
                            example: true
                          crf:
                            type: boolean
                            example: true
              examples:
                get_api_config_private200Example:
                  summary: Default get_api_config_private 200 response
                  x-microcks-default: true
                  value:
                    status: ok
                    message: Example response
        '401':
          $ref: '#/components/responses/Unauthorized'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Config
components:
  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Unauthorized
