openapi: 3.2.0
info:
  title: epa-csb-server User API
  version: 8.1.0
  license:
    name: CC0-1.0
  description: U.S. EPA CSB Rebate Forms Application
tags:
- name: User
paths:
  /api/user:
    get:
      summary: Get user data from EPA Gateway/Login.gov.
      parameters: []
      responses:
        '200':
          description: An object with a user's data from EPA Gateway/Login.gov.
          content:
            application/json:
              schema:
                type: object
                properties:
                  mail:
                    type: string
                    example: last.first@epa.gov
                  memberof:
                    type: string
                    example: csb_admin,csb_helpdesk
                  exp:
                    type: number
                    example: 1661376902
              examples:
                get_api_user200Example:
                  summary: Default get_api_user 200 response
                  x-microcks-default: true
                  value:
                    status: ok
                    message: Example response
        '401':
          $ref: '#/components/responses/Unauthorized'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - User
components:
  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Unauthorized
